name: CI
on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    
jobs:
  package_integrity_be:
    runs-on: ubuntu-latest
  
    strategy: 
      matrix:
        node-version: [20.x]
            
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd yapper-be
          npm install

  build_fe:
    runs-on: ubuntu-latest
  
    strategy: 
      matrix:
        node-version: [20.x]
            
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd yapper-fe
          npm install
          npm run build
    